FROM ubi8/ubi:8.5

MAINTAINER pp <pp@email>

LABEL description="test"

RUN yum install -y httpd && yum clean all

RUN echo "test" > /var/www/html/index.html

EXPOSE 80

CMD ["httpd","-D","FOREGROUND"]




