FROM ubi8/ubi:8.5

MAINTAINER pp <pp@emailc.om>

ENV PORT 8080

RUN yum install -y httpd && yum clean all

#RUN sed -i 's/8080/80' /etc/httpd/conf/httpd.conf

RUN sed -ri -e "/^Listen 80/c\Listen ${PORT}" /etc/httpd/conf/httpd.conf

RUN chown -R apache:apache /etc/httpd/logs && chown -R apache:apache /run/httpd

EXPOSE ${PORT}

COPY ./src/ /var/www/html/

CMD ["httpd", "-D", "FOREGROUND"]
